### ISSUE TITLE
runtime error occurs when assign value to array with index greater than its length.

### ISSUE THREAD

**Issue by sisshiki1969** [maekawatoshiki/rapidus#10]
It seems a bug in vm.set_member() function.

```Rust
    ValueBase::Number(n) if n - n.floor() == 0.0 => {
        if n as usize >= map.length as usize {
            map.length = n as usize;
            map.elems.set_len(n as usize);
        }
        map.elems[n as usize] = val;    // <= index out of bounds
    }
```
ex)
```javascript
var ary = []
console.log(ary[5] = 4)
```
```
$ node array.js
4
$ cargo run array.js
    Finished dev [unoptimized + debuginfo] target(s) in 0.15s
     Running `target/debug/rapidus array.js`
thread 'main' panicked at 'index out of bounds: the len is 5 but the index is 5', /rustc/96064eb61dc703c289fae61bdf90593d3e7b2449/src/libcore/slice/mod.rs:2454:14
note: Run with `RUST_BACKTRACE=1` for a backtrace.
thread 'main' panicked at 'exited. status: 101', src/main.rs:177:25
note: Run with `RUST_BACKTRACE=1` for a backtrace.
```

**Comment by maekawatoshiki** [comment]
fixed
